### ISSUE TITLE
How to update the firmware of my Panasonic PT-AT6000E?

### ISSUE THREAD

**Issue by beuaaa** [dineshpannu/panasonic-projector-serial#1]
This is not really an issue but rather a request for help. It's ok if you delete this message.

I think I have  a problem on my Panasonic PT-AT6000E that could be addressed in a firmware update ..... but it seems that the only way to update the firmware is to send it back to Panasonic.

Do you know how to update the firmware of Panasonic PT-AT6000E?
I read that it can be done using ORCA11.exe but I couldn't find it.

**Comment by dineshpannu** [comment]
I haven't had any experience updating firmware for this model. Your best bet is to ask on an AV forum like avsforum.com.

Not really relevant to this project so closing this ticket.
